Repository mcgivrer/ufo, pull requests merged in 2020-11, with the labels that each got.

#6 Feature/add render
  index.html
  modules/game.mjs
  modules/layer.mjs
  modules/main.mjs
  modules/render.mjs
  modules/scene.mjs
  styles/main.css
Labels: enhancement

#7 feat(physicengine): Add a PhysicEngine service
  modules/ball.mjs
  modules/demoscene.mjs
  modules/game.mjs
  modules/gameobject.mjs
  modules/physicengine.mjs
  modules/render.mjs
  modules/scene.mjs
Labels: enhancement

#10 Add a Gitter chat badge to README.md
  README.md
Labels: documentation, help wanted, question

#12 Feature/add doc file
  README.md
  doc/book.md
  modules/ball.mjs
  modules/demoscene.mjs
  modules/render.mjs
Labels: documentation
